### ISSUE TITLE
[FEATURE] per-domain configuration options

### ISSUE THREAD

**Issue by MEschenbacher** [saltstack-formulas/dehydrated-formula#6]
### Is your feature request related to a problem?

I'd like to use the [per-domain configuration options](https://github.com/dehydrated-io/dehydrated/blob/4fd777e87e589652b1127b79ac6688ed7cb151fe/docs/examples/config#L48)  via the formula.

### Describe the solution you'd like

The pillar could look like this

```yaml
dehydrated:
  domains:
    - example.org
  config:
    key_algo: rsa
  lookup:
  domainconfig:
    example.org:
      key_algo: secp384r1
```

### Describe alternatives you've considered

I guess I *could* place per-domain configuration files myself.
